// Mocks generated by Mockito 5.0.15 from annotations
// in csp_mobile_app/test/test_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'A.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [A].
///
/// See the documentation for Mockito's code generation for more information.
class MockA extends _i1.Mock implements _i2.A {
  MockA() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int a(int? x) =>
      (super.noSuchMethod(Invocation.method(#a, [x]), returnValue: 0) as int);
  @override
  String toString() => super.toString();
}
